#define MICROPY_HW_BOARD_NAME "M5Stack CoreS3 SE (LVGL Snapshot)"
#define MICROPY_HW_MCU_NAME "ESP32S3"

#define MICROPY_HW_ENABLE_SDCARD (1)
#define MICROPY_PY_MACHINE_I2S (1)
#define MICROPY_HW_ESP_USB_SERIAL_JTAG (1)
#define MICROPY_HW_USB_CDC (0)
